// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knehajxvfpfazohegggs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZWhhanh2ZnBmYXpvaGVnZ2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODgwMTksImV4cCI6MjA3MDU2NDAxOX0.9ItA-0wCsz93Fqif6VLcwR5l5MnVb2ibemjYSliveAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});